language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "14"
deploy:
  provider: script
  script: npm install && npm run deploy
  skip_cleanup: true
  on:
    branch: master
